=== SOC-CMCTS/fn_pa_firewall/payload_samples/palo_alto_firewall_create_a_new_tag/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "palo_alto_firewall_tag_name": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== SOC-CMCTS/fn_pa_firewall/payload_samples/palo_alto_firewall_view_all_globalprotect_users/output_json_example.json
{
    "version": 2.0,
    "success": true,
    "reason": null,
    "content": {
        "status": "success",
        "message": "Viewing all GlobalProtect users succeeded. \n <br><pre>|&nbsp;Username&nbsp;&nbsp;&nbsp;|&nbsp;Computer&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Virtual&nbsp;IP&nbsp;&nbsp;|&nbsp;Public&nbsp;IP&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Login&nbsp;Time&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<pre><br>|&nbsp;Johndoe&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;LAPTOP-1&nbsp;|&nbsp;192.168.16.12&nbsp;|&nbsp;123.123.123.132&nbsp;|&nbsp;Mar.09&nbsp;09:52:59&nbsp;|<br><pre>+------------+-------------------+-------------+--------------+-----------------+<pre><br>|&nbsp;Johndoe&nbsp;|&nbsp;LAPTOP-2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;192.168.16.43&nbsp;|&nbsp;123.123.123.132&nbsp;|&nbsp;Mar.09&nbsp;08:01:20&nbsp;|<br><pre>+------------+-------------------+-------------+--------------+-----------------+<pre><br>|&nbsp;Johndoe&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;LAPTOP-3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;192.168.16.37&nbsp;|&nbsp;123.123.123.132&nbsp;|&nbsp;Mar.09&nbsp;08:01:44&nbsp;|<br><pre>+------------+-------------------+-------------+--------------+-----------------+<pre><br>|&nbsp;Janie&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;LAPTOP-4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;192.168.16.13&nbsp;|&nbsp;123.123.123.132&nbsp;|&nbsp;Mar.09&nbsp;10:17:38&nbsp;|<br><pre>+------------+-------------------+-------------+--------------+-----------------+<pre><br>|&nbsp;thegun&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;LAPTOP-5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;192.168.16.15&nbsp;|&nbsp;123.123.123.132&nbsp;|&nbsp;Mar.09&nbsp;09:16:20&nbsp;|<br><pre>+------------+-------------------+-------------+--------------+-----------------+<pre><br>"
    },
    "raw": null,
    "inputs": {},
    "metrics": {
        "version": "1.0",
        "package": "fn-pa-firewall",
        "package_version": "1.0.0",
        "host": "LAPTOP-5",
        "execution_time_ms": 360,
        "timestamp": "2023-03-09 10:17:46"
    }
}

=== SOC-CMCTS/fn_pa_firewall/payload_samples/palo_alto_firewall_create_a_new_tag/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "status": "success",
    "message": "Create a new tag \"dmlong-create-a-new-tag-name\" succeeded."
  },
  "raw": null,
  "inputs": {
    "palo_alto_firewall_tag_name": "dmlong-create-a-new-tag-name"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-pa-firewall",
    "package_version": "1.0.0",
    "host": "DMLONG-LAP",
    "execution_time_ms": 1321,
    "timestamp": "2023-03-09 10:10:25"
  }
}

=== SOC-CMCTS/fn_pa_firewall/payload_samples/palo_alto_firewall_delete_an_ip_address_object/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "status": "success",
    "message": "Delete IP address object \"blacklist-45.150.64.88\" succeeded."
  },
  "raw": null,
  "inputs": {
    "palo_alto_firewall_address_objects_name": "blacklist-45.150.64.88"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-pa-firewall",
    "package_version": "1.0.0",
    "host": "DMLONG-LAP",
    "execution_time_ms": 818,
    "timestamp": "2023-03-09 10:16:04"
  }
}
